---
abstract: 'Asynchronous ZeroMQ sockets for POE'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  Test::More: 0.96
configure_requires:
  Devel::CheckLib: 0.9
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-ZMQ
no_index:
  directory:
    - tools
    - examples
recommends:
  Convert::Z85: 0
requires:
  Exporter::Tiny: 0
  FFI::Raw: 0
  Import::Into: 0
  List::Objects::Types: 1.002
  List::Objects::WithUtils: 2.013
  Math::Int64: 0
  Module::Runtime: 0
  Moo: 1
  MooX::Role::POE::Emitter: 0.12
  MooX::late: 0.014
  POE: 0
  POSIX: 0
  Throwable: 0
  Time::HiRes: 0
  Try::Tiny: 0
  Type::Tiny: 0.04
  namespace::clean: 0
  perl: v5.16.0
  strictures: 1
resources:
  repository: git://github.com/avenj/poex-zmq.git
version: 0.005002
